[package]
name = "splight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
inputbot = "0.5.1"
egui = "0.18.1"
eframe = "0.19.0"